jobs:
  - id: 1
    name: "Извлечение данных из источника A"
    dependencies: []

  - id: 2
    name: "Извлечение данных из источника B"
    dependencies: []

  - id: 3
    name: "Обработка данных A"
    dependencies: [1]

  - id: 4
    name: "Обработка данных B"
    dependencies: [2]
    
  # Этот джоб намеренно вызовет ошибку для демонстрации
  - id: 5
    name: "Агрегация данных A и B (с ошибкой)"
    dependencies: [3, 4]
    fail: true # Пользовательский флаг для симуляции ошибки

  - id: 6
    name: "Формирование отчета"
    dependencies: [5]

  - id: 7
    name: "Отправка отчета"
    dependencies: [6]